### PR TITLE
Simplified issue templates

### PR DESCRIPTION
**Pull request by jbednar**
- Tell people to delete the explanatory text (otherwise reports are very noisy!)
- Use same formatting for bug reports and feature requests
- Tell people not to open custom issues (which they can ignore, but at least we told them!)

### CODE REVIEW

**Comment by philippjfr** [comment]
We could also do what bokeh did and delete the custom template entirely since us developers can just delete the other templates.

**Comment by jbednar** [comment]
Hard to say what's better in that respect.  No matter what we do, Github will provide a link "Don’t see your issue here? Open a blank issue.", which gives no info at all, and this way people will at least be told "Don't open a custom issue" when they click on "custom issue". They can always ignore that instruction, but at least there's been some communication that issues are _only_ for feature requests and bug reports...

**Comment by philippjfr** [comment]
Fair point, that said I hadn't ever noticed the "Open a blank issue" link on the page, then again maybe that's just because I always immediately clicked on "custom issue".

**Review by ceball — APPROVED** [review]
I PREFER THE FRIENDLIER INTRODUCTION :)

**Comment by ceball** [comment]
I think I discovered that problem with the custom issue when I tried not having it in the past. Since then, I have noticed this: 

> You can require contributors to use issue templates by setting blank_issues_enabled to false.

https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

**Comment by ceball** [comment]
In case anyone feels strong, I also have this outstanding note:

> I created a SUPPORT.md file in holoviz org .github repo, but it doesn’t seem to have done anything - seems not useful. Must have misread that github page (https://help.github.com/en/github/building-a-strong-community/adding-support-resources-to-your-project).

New contributors might see a different view of things from previous contributors, not sure.

**Comment by jbednar** [comment]
> You can require contributors to use issue templates by setting blank_issues_enabled to false.

That would only work if we could somehow tell them what to do instead of opening an issue.  It sounds like SUPPORT.md would allow that?  I don't see a file SUPPORT.md on the [holoviz/holoviz repo](https://github.com/holoviz/holoviz); did you delete it once you saw it didn't work?

**Comment by ceball** [comment]
> I don't see a file SUPPORT.md on the holoviz/holoviz repo; did you delete it once you saw it didn't work

I put it in the holoviz .github repo (not holoviz/holoviz) as it's supposed to be the default for all org repos that don't have their own to override it (as per https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file): 
  * https://github.com/holoviz/.github/blob/master/SUPPORT.md 

> You can add default community health files to the root of a public repository called .github that is owned by an organization or user account.
> [...]
>  Issue templates and their configuration file must be in a folder called .github/ISSUE_TEMPLATE. All other supported files must be in the root of the repository.

**Comment by ceball** [comment]
>> You can require contributors to use issue templates by setting blank_issues_enabled to false.
>
> That would only work if we could somehow tell them what to do instead of opening an issue. 

The next but one sentence on that page is:

> If you prefer to receive certain reports outside of GitHub, you can direct people to external sites with contact_links.
> 
> Here is an example config.yml file.
> 
> blank_issues_enabled: false
> contact_links:
>  - name: GitHub Community Forum
>    url: https://github.community/
>    about: Please ask and answer questions here.
>  - name: GitHub Security Bug Bounty
>    url: https://bounty.github.com/
>    about: Please report security vulnerabilities here.

(I can't wrap my head around it all...for me, the only way is to try and see what happens!)

**Comment by jbednar** [comment]
Ok, I've added a config.yml as described at https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository and disabled blank issues. We'll see if that works!

**Comment by jbednar** [comment]
I don't think we can tell how it works until I merge, so I'll try it. We can revert if we aren't happy with it.

**Comment by jbednar** [comment]
Looks like it works, and I can delete the custom issue template:

image

**Comment by jbednar** [comment]
Additional changes were applied in https://github.com/holoviz/.github/pull/3, which I just merged. A user who opens a new issue now sees only three options, with Discourse being the only open-ended one:

image

Opening a bug report leads to:

image

Opening a feature request leads to:

image

And of course the last link leads to Discourse.  Seems ok to me now, but please open a PR if you want any additional changes. Thanks for the feedback and suggestions!

**Comment by ceball** [comment]
Great! And thanks for battling through it!

**Pull request merged**
